### ISSUE TITLE
Horizontal scrollbar is annoying and unncessary

### ISSUE THREAD

**Issue by rajivpo** [Uniswap/uniswap-io#1]
I don't have access to push to this repo, but would suggest removing `width: 100vw;` from `AppWrapper` in `index.js`

**Comment by NoahZinsmeister** [comment]
happy to look at a PR :)

**Comment by rajivpo** [comment]
Happy to make one! Since there isn't push access to the repo, should I just fork and make the PR across the fork?

**Comment by NoahZinsmeister** [comment]
yes please!
